pull_request_rules:
  - name: Upgrade deps
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=development
      - label=dependencies
    actions:
      delete_head_branch:
        force: false
      merge:
        method: rebase
