# 毎週日曜日0時に実行される、依存関係の自動アップグレード
name: Auto Upgrade

on:
  schedule:
    - cron: '0 15 * * 0'

jobs:
  auto-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Upgrade package.json, yarn.lock
        run: yarn upgrade --latest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Upgrade deps
          title: Upgrade deps
          labels: dependencies
          branch-suffix: 'short-commit-hash'
