name: Otherpref Data Update

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  auto-update:
    name: Update
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: development

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Download File
        run: 'curl https://script.google.com/macros/s/AKfycby_JZ_sqx8BefQRPOq5AVwt2wMbiazNmYnEeMo--_e8qwqQwNQ/exec?data=forked_sites -L -o otherpref.csv'
        working-directory: ./opendata

      - name: Convert to JSON
        run: 'python ../workflow_tools/csv2json/main.py'
        working-directory: ./opendata
        env:
          FILE: otherpref

      - name: Move JSON to ./data
        run: 'mv otherpref.json ../data/otherpref.json -u && cd ../'
        working-directory: ./opendata

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update otherpref.json
          title: Update otherpref
          labels: auto_merge
          branch-suffix: 'short-commit-hash'