name: Pull Request Labeler

on:
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label for Auto-merge
      if: github.actor == 'transifex-integration[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'github-actions[bot]'
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"